package persist

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Snapshot is what CloneForRead returns: the on-disk working tree
// directory and the snapshot's identity for caching.
//
// Dir is the local working tree. "" means no data (branch missing on
// origin, or scratch dir absent in dev mode); SHA is "" in that case
// too.
//
// SHA is the commit at the tip of the data branch (40-char hex).
// Used by callers as the key against which to compare a previously-
// recorded "last hydrated SHA" — when they match, no walk is needed.
// "" in dev mode (file backend has no commit identity).
//
// Reset is true when the local persistent cache was force-reset to
// match a rewritten remote — typically after `defrost drop history`
// rewrites the data branch via orphan commit. Callers that maintain
// derived state (DuckDB rows, hydration_state) MUST drop and rebuild
// that state when Reset is true.
type Snapshot struct {
	Dir   string
	SHA   string
	Reset bool
}

// LocalDir is the per-repo home for everything defrost stores
// outside the data branch — read-side worktree, DuckDB cache,
// suppressions, and (future) user config. Lives inside the user's
// working tree so it's bound by the repo, naturally per-repo, and
// the things that should be reviewed (suppressions, config) commit
// alongside the rest of the project.
//
// Layout under <repoDir>/.defrost/:
//
//	.gitignore           auto-created on first init; ignores data/ and cache.duckdb
//	data/                persistent worktree of the data branch (gitignored)
//	cache.duckdb         DuckDB read cache (gitignored)
//	suppressions.json    committed: shared list of suppressed test IDs
const LocalDir = ".defrost"

// localGitignore is the auto-generated content for
// <repoDir>/.defrost/.gitignore. Idempotent — EnsureLocalDir
// only writes it when missing so users can extend the file
// without us clobbering their additions.
const localGitignore = `# Auto-generated by defrost. See https://github.com/bjk95/defrost
# Anything tracked here is intentionally committed (suppressions,
# config). Per-machine artefacts live in data/ and cache.duckdb.
/data
/cache.duckdb
/cache.duckdb.wal
`

// LocalRoot returns <repoDir>/.defrost — the per-repo home defrost
// uses for the persistent worktree, DuckDB cache, and committed
// config (suppressions and friends).
//
// In dev mode and prod mode the path is identical; the only
// difference between the two is whether the data branch gets
// pushed/fetched against origin.
func LocalRoot(opts Options) string {
	repo := opts.RepoDir
	if repo == "" {
		repo = "."
	}
	return filepath.Join(repo, LocalDir)
}

// CacheRoot is kept as an alias for LocalRoot to ease the transition
// for callers that adopted the older name. New code should call
// LocalRoot directly.
func CacheRoot(opts Options) (string, error) { return LocalRoot(opts), nil }

// LocalDataDir is the worktree path inside LocalRoot.
//
//	<repoDir>/.defrost/data/
//
// In prod mode this is a clone of the data branch (with .git inside).
// In dev mode it's a plain directory of OTLP files. Both share the
// same path so reading code (DuckDB hydrate, history) doesn't have
// to branch on mode.
func LocalDataDir(opts Options) string { return filepath.Join(LocalRoot(opts), "data") }

// LocalSuppressionsPath is the path to the committed suppressions
// list. Suppressions live in the user's working tree (not on the
// data branch) so that `defrost suppress add` produces a reviewable
// diff in the user's normal PR workflow.
func LocalSuppressionsPath(opts Options) string {
	return filepath.Join(LocalRoot(opts), suppressionsFile)
}

// EnsureLocalDir creates <repoDir>/.defrost/ if missing and writes
// a default .gitignore the first time. Existing .gitignore content
// is preserved — we only write when the file is absent.
func EnsureLocalDir(opts Options) error {
	root := LocalRoot(opts)
	if err := os.MkdirAll(root, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", root, err)
	}
	gi := filepath.Join(root, ".gitignore")
	if _, err := os.Stat(gi); err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		if err := os.WriteFile(gi, []byte(localGitignore), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", gi, err)
		}
	}
	return nil
}

// dataCacheDir is the worktree path the gitBackend persists into.
func (b *gitBackend) dataCacheDir() (string, error) {
	return LocalDataDir(b.opts), nil
}

// RemoteHeadSHA returns the commit SHA at the tip of the data branch
// on origin. Returns ("", nil) when the branch doesn't exist on
// origin — the caller treats that as "no data yet."
//
// Cheap (one HTTPS round-trip via `git ls-remote`); intended as the
// freshness probe before any clone/fetch.
func (b *gitBackend) RemoteHeadSHA() (string, error) {
	branch := b.dataBranch()
	remoteURL, err := resolveTargetURL(b.opts)
	if err != nil {
		return "", err
	}
	out, err := runGit("", "ls-remote", remoteURL, "refs/heads/"+branch)
	if err != nil {
		var ge *gitErr
		if errors.As(err, &ge) && ge.code == 2 {
			return "", nil
		}
		return "", fmt.Errorf("ls-remote %s: %w", remoteURL, err)
	}
	out = strings.TrimSpace(out)
	if out == "" {
		return "", nil
	}
	parts := strings.Fields(out)
	if len(parts) < 1 {
		return "", nil
	}
	return parts[0], nil
}

// fileBackend has no remote, so the SHA probe is always empty.
func (b *fileBackend) RemoteHeadSHA() (string, error) { return "", nil }

// localHeadSHA returns the SHA at HEAD inside the persistent worktree
// at dir, or "" if dir doesn't yet contain a checkout.
func localHeadSHA(dir string) string {
	if _, err := os.Stat(filepath.Join(dir, ".git")); err != nil {
		return ""
	}
	out, err := runGit(dir, "rev-parse", "HEAD")
	if err != nil {
		return ""
	}
	return strings.TrimSpace(out)
}

// removeAllPreservingParent rm -rf's path but keeps its parent dir.
func removeAllPreservingParent(path string) error {
	if path == "" {
		return nil
	}
	if err := os.RemoveAll(path); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	return nil
}
